### ISSUE TITLE
Automatically create subdirectory for logs?

### ISSUE THREAD

**Issue by mhujer** [mangoweb-backend/monolog-tracy-handler#4]
Hello,

I was wondering if it is intentional to not create a subdirectory for storing the generated `.html` files when the `$localBlueScreenDirectory` is configured to something like `'%kernel.logs_dir%/tracy'`? 

I checked the `StreamHandler` from the Monolog and it attempts to create a directory where the logs should be placed: https://github.com/Seldaek/monolog/blob/c1971982c3b792e488726468046b1ef977934c6a/src/Monolog/Handler/StreamHandler.php#L100

**Comment by JanTvrdik** [comment]
I don't remember but I would be fine with merging a PR which would auto-create the directory if missing.
