### ISSUE TITLE
Monolog v3 support 

### ISSUE THREAD

**Issue by simPod** [mangoweb-backend/monolog-tracy-handler#6]
Hello is anyone working on monolog v3 support or should I look into it? Thanks.

**Comment by JanTvrdik** [comment]
Why closed?

**Comment by simPod** [comment]
I suggested to implement it but I won't pursue it unfortunately. There's too much work to be done on this lib before it can be supported I believe.

**Comment by JanTvrdik** [comment]
You can test the implemenation in master https://github.com/mangoweb-backend/monolog-tracy-handler/commit/5ed2e84617a39220b73df114fb83222c6d9af820

**Comment by simPod** [comment]
thanks for lib bump
